//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.24 at 04:35:32 PM MSK 
//


package com.itrail.soap.genereated.patients;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.itrail.soap.genereated.patients package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.itrail.soap.genereated.patients
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPatientRequestFindById }
     * 
     */
    public GetPatientRequestFindById createGetPatientRequestFindById() {
        return new GetPatientRequestFindById();
    }

    /**
     * Create an instance of {@link GetPatientRequestFindAll }
     * 
     */
    public GetPatientRequestFindAll createGetPatientRequestFindAll() {
        return new GetPatientRequestFindAll();
    }

    /**
     * Create an instance of {@link GetPatientRequestAdd }
     * 
     */
    public GetPatientRequestAdd createGetPatientRequestAdd() {
        return new GetPatientRequestAdd();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link GetPatientResponse }
     * 
     */
    public GetPatientResponse createGetPatientResponse() {
        return new GetPatientResponse();
    }

    /**
     * Create an instance of {@link GetPatient }
     * 
     */
    public GetPatient createGetPatient() {
        return new GetPatient();
    }

}
