//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.24 at 04:35:32 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/itrail/soap/genereated/documents", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.itrail.soap.genereated.documents;
